language: php

matrix:
  include:
    - php: 5.5.9
      dist: trusty
      env: LARAVEL_VERSION=5.1.*
    - php: 5.5
      dist: trusty
      env: LARAVEL_VERSION=5.1.*
    - php: 5.5
      dist: trusty
      env: LARAVEL_VERSION=5.2.*
    - php: 5.6
      dist: xenial
      env: LARAVEL_VERSION=5.1.*
    - php: 5.6
      dist: xenial
      env: LARAVEL_VERSION=5.2.*
    - php: 5.6
      dist: xenial
      env: LARAVEL_VERSION=5.3.*
    - php: 5.6
      dist: xenial
      env: LARAVEL_VERSION=5.4.*
    - php: 7.0
      dist: xenial
      env: LARAVEL_VERSION=5.1.*
    - php: 7.0
      dist: xenial
      env: LARAVEL_VERSION=5.2.*
    - php: 7.0
      dist: xenial
      env: LARAVEL_VERSION=5.3.*
    - php: 7.0
      dist: xenial
      env: LARAVEL_VERSION=5.4.*
    - php: 7.0
      dist: xenial
      env: LARAVEL_VERSION=5.5.*
    - php: 7.1
      dist: bionic
      env: LARAVEL_VERSION=5.3.*
    - php: 7.1
      dist: bionic
      env: LARAVEL_VERSION=5.4.*
    - php: 7.1
      dist: bionic
      env: LARAVEL_VERSION=5.5.*
    - php: 7.1
      dist: bionic
      env: LARAVEL_VERSION=5.6.*
    - php: 7.1
      dist: bionic
      env: LARAVEL_VERSION=5.7.*
    - php: 7.1
      dist: bionic
      env: LARAVEL_VERSION=5.8.*
    - php: 7.2
      dist: bionic
      env: LARAVEL_VERSION=5.5.*
    - php: 7.2
      dist: bionic
      env: LARAVEL_VERSION=5.6.*
    - php: 7.2
      dist: bionic
      env: LARAVEL_VERSION=5.7.*
    - php: 7.2
      dist: bionic
      env: LARAVEL_VERSION=5.8.*
    - php: 7.2
      dist: bionic
      env: LARAVEL_VERSION=6.0
    - php: 7.2
      dist: bionic
      env: LARAVEL_VERSION=7.0
    - php: 7.2
      dist: bionic
      env: LARAVEL_VERSION=6.*
    - php: 7.2
      dist: bionic
      env: LARAVEL_VERSION=7.*
    - php: 7.3
      dist: bionic
      env: LARAVEL_VERSION=5.5.*
    - php: 7.3
      dist: bionic
      env: LARAVEL_VERSION=5.6.*
    - php: 7.3
      dist: bionic
      env: LARAVEL_VERSION=5.7.*
    - php: 7.3
      dist: bionic
      env: LARAVEL_VERSION=5.8.*
    - php: 7.3
      dist: bionic
      env: LARAVEL_VERSION=6.*
    - php: 7.3
      dist: bionic
      env: LARAVEL_VERSION=7.*
    - php: 7.3
      dist: bionic
      env: LARAVEL_VERSION=8.*
    - php: 7.4
      dist: bionic
      env: LARAVEL_VERSION=5.8.*
    - php: 7.4
      dist: bionic
      env: LARAVEL_VERSION=6.0
    - php: 7.4
      dist: bionic
      env: LARAVEL_VERSION=7.0
    - php: 7.4
      dist: bionic
      env: LARAVEL_VERSION=6.*
    - php: 7.4
      dist: bionic
      env: LARAVEL_VERSION=7.*
    - php: 7.4
      dist: bionic
      env: LARAVEL_VERSION=8.*
    - addons:
        apt:
          packages:
            - docker-ce
      sudo: required
      sevices:
        - docker
      rvm: 2.4.1
      before_install: ruby --version
      install: bundle install
      script: bundle exec bugsnag-maze-runner -c
      env: LARAVEL_FIXTURE=laravel56
    - addons:
        apt:
          packages:
            - docker-ce
      sudo: required
      sevices:
        - docker
      rvm: 2.4.1
      before_install: ruby --version
      install: bundle install
      script: bundle exec bugsnag-maze-runner -c
      env: LARAVEL_FIXTURE=laravel58
    - addons:
        apt:
          packages:
            - docker-ce
      sudo: required
      sevices:
        - docker
      rvm: 2.4.1
      before_install: ruby --version
      install: bundle install
      script: bundle exec bugsnag-maze-runner -c
      env: LARAVEL_FIXTURE=laravel66

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer require "laravel/framework:${LARAVEL_VERSION}" --no-update
  - echo "memory_limit=4G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - if [[ $TRAVIS_PHP_VERSION == 5.5.9 ]]; then travis_retry composer update --no-interaction --prefer-dist --prefer-lowest ; fi
  - if [[ $TRAVIS_PHP_VERSION != 5.5.9 ]]; then travis_retry composer update --no-interaction --prefer-dist ; fi
  - composer show laravel/framework

script:
  - make test
