language: php

sudo: false

matrix:
  include:
    - php: 5.5.9
      env:
        - GUZZLE_VERSION=^5.3
        - LARAVEL_VERSION=5.1.*
    - php: 5.5.9
      env:
        - GUZZLE_VERSION=^6.0
        - LARAVEL_VERSION=5.1.*
    - php: 5.5
      env:
        - GUZZLE_VERSION=^5.3
        - LARAVEL_VERSION=5.1.*
    - php: 5.5
      env:
        - GUZZLE_VERSION=^6.0
        - LARAVEL_VERSION=5.1.*
    - php: 5.6
      env:
        - GUZZLE_VERSION=^5.3
        - LARAVEL_VERSION=5.4.*
    - php: 5.6
      env:
        - GUZZLE_VERSION=^6.0
        - LARAVEL_VERSION=5.4.*
    - php: 7.0
      env:
        - GUZZLE_VERSION=^5.3
        - LARAVEL_VERSION=5.5.*
    - php: 7.0
      env:
        - GUZZLE_VERSION=^6.0
        - LARAVEL_VERSION=5.5.*
    - php: 7.1
      env:
        - GUZZLE_VERSION=^5.3
        - LARAVEL_VERSION=5.5.*
    - php: 7.1
      env:
        - GUZZLE_VERSION=^6.0
        - LARAVEL_VERSION=5.5.*
    - php: 7.1
      env:
        - GUZZLE_VERSION=^5.3
        - LARAVEL_VERSION=5.6.*
    - php: 7.1
      env:
        - GUZZLE_VERSION=^6.0
        - LARAVEL_VERSION=5.6.*
    - php: 7.2
      env:
        - GUZZLE_VERSION=^5.3
        - LARAVEL_VERSION=5.5.*
    - php: 7.2
      env:
        - GUZZLE_VERSION=^6.0
        - LARAVEL_VERSION=5.5.*
    - php: 7.2
      env:
        - GUZZLE_VERSION=^5.3
        - LARAVEL_VERSION=5.6.*
    - php: 7.2
      env:
        - GUZZLE_VERSION=^6.0
        - LARAVEL_VERSION=5.6.*
    - php: hhvm-3.6
      sudo: required
      dist: trusty
      group: edge
      env:
        - GUZZLE_VERSION=^5.3
        - LARAVEL_VERSION=5.1.*
    - php: hhvm-3.6
      sudo: required
      dist: trusty
      group: edge
      env:
        - GUZZLE_VERSION=^6.0
        - LARAVEL_VERSION=5.1.*
    - php: hhvm-3.9
      sudo: required
      dist: trusty
      group: edge
      env:
        - GUZZLE_VERSION=^5.3
        - LARAVEL_VERSION=5.1.*
    - php: hhvm-3.9
      sudo: required
      dist: trusty
      group: edge
      env:
        - GUZZLE_VERSION=^6.0
        - LARAVEL_VERSION=5.1.*
    - php: hhvm-3.12
      sudo: required
      dist: trusty
      group: edge
      env:
        - GUZZLE_VERSION=^5.3
        - LARAVEL_VERSION=5.1.*
    - php: hhvm-3.12
      sudo: required
      dist: trusty
      group: edge
      env:
        - GUZZLE_VERSION=^6.0
        - LARAVEL_VERSION=5.1.*
    - addons:
        apt:
          packages:
          - docker-ce
      sudo: required
      sevices:
      - docker
      rmv: 2.4.1
      install: bundle install
      script: bundle exec bugsnag-maze-runner -c

before_install:
  - if [[ $TRAVIS_PHP_VERSION =~ ^hhvm ]]; then echo 'hhvm.jit = false' >> /etc/hhvm/php.ini ; fi
  - composer require "guzzlehttp/guzzle:${GUZZLE_VERSION}" --no-update
  - composer require "laravel/framework:${LARAVEL_VERSION}" --no-update

install:
  - if [[ $TRAVIS_PHP_VERSION == 5.5.9 ]]; then travis_retry composer update --no-interaction --prefer-source --prefer-lowest ; fi
  - if [[ $TRAVIS_PHP_VERSION != 5.5.9 ]]; then travis_retry composer update --no-interaction --prefer-source ; fi

script:
  - make test
